<a href="https://colab.research.google.com/github/Samia35-2973/Machine-Learning-Notes/blob/main/titanic_decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [Titanic Kaggle Competition](https://www.kaggle.com/competitions/titanic/overview)

In [1065]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree
import math

In [1066]:
df = pd.read_csv('train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [1067]:
d = df[['Pclass', 'Sex', 'Age', 'Fare', 'Survived']]
d

Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

In [1068]:
# to check if any row of this column has nan value
d['Pclass'].isna().any()

False

In [1069]:
d['Sex'].isna().any()

False

In [1070]:
d['Age'].isna().any()

True

In [1071]:
d['Fare'].isna().any()

False

In [1072]:
d['Survived'].isna().any()

False

In [1073]:
# since age has nan value so we will take mean value of it
mean_age = math.floor(d['Age'].mean())
mean_age

29

In [1074]:
d['Age'] = d['Age'].fillna(mean_age)
d

<ipython-input-1074-ea017f09a12f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d['Age'] = d['Age'].fillna(mean_age)


Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female  29.0  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

In [1075]:
d['Age'].isna().any()

False

In [1076]:
le = LabelEncoder()

In [1077]:
d['Sex'] = le.fit_transform(d['Sex'])
d

<ipython-input-1077-bfe6c662420b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d['Sex'] = le.fit_transform(d['Sex'])


Pclass  Sex   Age     Fare  Survived
0         3    1  22.0   7.2500         0
1         1    0  38.0  71.2833         1
2         3    0  26.0   7.9250         1
3         1    0  35.0  53.1000         1
4         3    1  35.0   8.0500         0
..      ...  ...   ...      ...       ...
886       2    1  27.0  13.0000         0
887       1    0  19.0  30.0000         1
888       3    0  29.0  23.4500         0
889       1    1  26.0  30.0000         1
890       3    1  32.0   7.7500         0

[891 rows x 5 columns]

In [1078]:
x_train = d[['Pclass', 'Sex', 'Age', 'Fare']].values
x_train

array([[ 3.    ,  1.    , 22.    ,  7.25  ],
       [ 1.    ,  0.    , 38.    , 71.2833],
       [ 3.    ,  0.    , 26.    ,  7.925 ],
       ...,
       [ 3.    ,  0.    , 29.    , 23.45  ],
       [ 1.    ,  1.    , 26.    , 30.    ],
       [ 3.    ,  1.    , 32.    ,  7.75  ]])

In [1079]:
ohe = OneHotEncoder()
ct = ColumnTransformer([('Pclass', ohe, [0])], remainder='passthrough')

In [1080]:
x_train = ct.fit_transform(x_train)

In [1081]:
x_train = x_train[:,1:]
x_train

array([[ 0.    ,  1.    ,  1.    , 22.    ,  7.25  ],
       [ 0.    ,  0.    ,  0.    , 38.    , 71.2833],
       [ 0.    ,  1.    ,  0.    , 26.    ,  7.925 ],
       ...,
       [ 0.    ,  1.    ,  0.    , 29.    , 23.45  ],
       [ 0.    ,  0.    ,  1.    , 26.    , 30.    ],
       [ 0.    ,  1.    ,  1.    , 32.    ,  7.75  ]])

In [1082]:
y_train = d[['Survived']].values
y_train

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [1083]:
model = tree.DecisionTreeClassifier(criterion='entropy')

In [1084]:
model.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [1085]:
test_df = pd.read_csv('test.csv')
test_df

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [1086]:
test_df['Pclass'].isna().any()

False

In [1087]:
test_df['Sex'].isna().any()

False

In [1088]:
test_df['Age'].isna().any()

True

In [1089]:
test_df['Fare'].isna().any()

True

In [1090]:
test_df['Age'] = test_df['Age'].fillna(math.floor(test_df['Age'].mean()))
test_df['Age'].isna().any()

False

In [1091]:
test_df['Fare'] = test_df['Fare'].fillna(math.floor(test_df['Fare'].mean()))
test_df['Fare'].isna().any()

False

In [1092]:
test_df['Sex'] = le.fit_transform(test_df['Sex'])
test_df

PassengerId  Pclass                                          Name  Sex  \
0            892       3                              Kelly, Mr. James    1   
1            893       3              Wilkes, Mrs. James (Ellen Needs)    0   
2            894       2                     Myles, Mr. Thomas Francis    1   
3            895       3                              Wirz, Mr. Albert    1   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    0   
..           ...     ...                                           ...  ...   
413         1305       3                            Spector, Mr. Woolf    1   
414         1306       1                  Oliva y Ocana, Dona. Fermina    0   
415         1307       3                  Saether, Mr. Simon Sivertsen    1   
416         1308       3                           Ware, Mr. Frederick    1   
417         1309       3                      Peter, Master. Michael J    1   

      Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0    34.5      0      0              330911    7.8292   NaN        Q  
1    47.0      1      0              363272    7.0000   NaN        S  
2    62.0      0      0              240276    9.6875   NaN        Q  
3    27.0      0      0              315154    8.6625   NaN        S  
4    22.0      1      1             3101298   12.2875   NaN        S  
..    ...    ...    ...                 ...       ...   ...      ...  
413  30.0      0      0           A.5. 3236    8.0500   NaN        S  
414  39.0      0      0            PC 17758  108.9000  C105        C  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416  30.0      0      0              359309    8.0500   NaN        S  
417  30.0      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [1093]:
ct2 = ColumnTransformer([('Pclass', ohe, [0])], remainder='passthrough')

In [1094]:
x_test = test_df[['Pclass', 'Sex', 'Age', 'Fare']].values
x_test

array([[ 3.    ,  1.    , 34.5   ,  7.8292],
       [ 3.    ,  0.    , 47.    ,  7.    ],
       [ 2.    ,  1.    , 62.    ,  9.6875],
       ...,
       [ 3.    ,  1.    , 38.5   ,  7.25  ],
       [ 3.    ,  1.    , 30.    ,  8.05  ],
       [ 3.    ,  1.    , 30.    , 22.3583]])

In [1095]:
x_test = ct2.fit_transform(x_test)
x_test = x_test[:, 1:]
x_test

array([[ 0.    ,  1.    ,  1.    , 34.5   ,  7.8292],
       [ 0.    ,  1.    ,  0.    , 47.    ,  7.    ],
       [ 1.    ,  0.    ,  1.    , 62.    ,  9.6875],
       ...,
       [ 0.    ,  1.    ,  1.    , 38.5   ,  7.25  ],
       [ 0.    ,  1.    ,  1.    , 30.    ,  8.05  ],
       [ 0.    ,  1.    ,  1.    , 30.    , 22.3583]])

In [1096]:
y_predicted = model.predict(x_test)

In [1097]:
predicted_df = pd.DataFrame(test_df['PassengerId'], columns=['PassengerId'])
predicted_df

PassengerId
0            892
1            893
2            894
3            895
4            896
..           ...
413         1305
414         1306
415         1307
416         1308
417         1309

[418 rows x 1 columns]

In [1098]:
predicted_df['Survived'] = y_predicted
predicted_df

PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         1
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

To export the result to submission.csv use to_csv method. Set index to false if excluding

In [1099]:
predicted_df.to_csv('submission.csv', index=False)